name: FinSight CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Instalar Dependências do Backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Executar Testes Automatizados (pytest)
      run: |
        pytest tests/

    - name: Build da Imagem Docker da API
      run: |
        docker build -t finsight-api:latest .